apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-07ak
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0016-tenant/tkrw-pr714-0075-0016-app/devfile-sample-07ak@sha256:ca5e06ba65b181147a893179a77494f43e9a25e98ad58059a4fe31141613d618
        name: my-nodejs
        resources: {}
status: {}
